name: Create Release

permissions: write-all

on:
  release:
    types: [ published, prereleased ]
  workflow_dispatch:

env:
  FLUTTER_CHANNEL: "stable"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - name: Get dependencies and perform prerequisites
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Decode Release Key
        run: |
          echo "$TUBESYNC_JKS" > syncara.b64
          base64 --decode syncara.b64 > syncara.jks
        env:
          TUBESYNC_JKS: ${{ secrets.TUBESYNC_JKS }}

      - name: Build Android Release
        run: flutter build apk --release && flutter build apk --release --split-per-abi
        env:
          TUBESYNC_KEY_PASSWORD: ${{ secrets.TUBESYNC_KEY_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-*.apk

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: syncara_android_release
          path: build/app/outputs/flutter-apk/app-*.apk
          compression-level: 9

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libmpv-dev libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Get dependencies and perform prerequisites
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build Linux Release
        run: flutter build linux --release

      - name: Prepare bundle
        run: |
          cd build/linux/x64/release/bundle
          zip -r syncara_linux.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/x64/release/bundle/syncara_linux.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: syncara_linux_release
          compression-level: 9
          path: |
            build/linux/x64/release/bundle/
            !build/linux/x64/release/bundle/syncara_linux.zip

  build-ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Get dependencies and perform prerequisites
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Prepare bundle
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app/ Payload
          zip -qq -r -9 syncara_ios_unsigned.ipa Payload

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: syncara_ios_unsigned.ipa

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: syncara_ios_release
          path: syncara_ios_unsigned.ipa
          compression-level: 9

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Get dependencies and perform prerequisites
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build MacOS Release
        run: flutter build macos --release

      - name: Prepare bundle
        run: |
          mv build/macos/Build/Products/Release/*.app ./
          zip -r syncara_macos.zip *.app

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: syncara_macos.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: syncara_macos_release
          compression-level: 9
          path: syncara_macos.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Get dependencies and perform prerequisites
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows Release
        run: |
          flutter build windows --release
          dart run msix:create

      - name: Prepare bundle
        run: |
          Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath "syncara_windows.zip"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            syncara_windows.zip
            build/windows/x64/runner/Release/*.msix

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: syncara_windows_release
          compression-level: 9
          path: |
            build/windows/x64/runner/Release/
            syncara_windows.zip